// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: wallet.proto

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClient interface {
	SettleHandle(ctx context.Context, in *SettleReq, opts ...grpc.CallOption) (*SettleResp, error)
	SettleCancel(ctx context.Context, in *SettleCancelReq, opts ...grpc.CallOption) (*SettleCancelResp, error)
	SettleConfirm(ctx context.Context, in *SettleConfirmReq, opts ...grpc.CallOption) (*SettleConfirmResp, error)
	Balance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*BalanceResp, error)
	DepositTry(ctx context.Context, in *DepositTryReq, opts ...grpc.CallOption) (*DepositTryResp, error)
	DepositCancel(ctx context.Context, in *DepositCancelReq, opts ...grpc.CallOption) (*DepositCancelResp, error)
	DepositConfirm(ctx context.Context, in *DepositConfirmReq, opts ...grpc.CallOption) (*DepositConfirmResp, error)
	WithdrawalTry(ctx context.Context, in *WithdrawalTryReq, opts ...grpc.CallOption) (*WithdrawalTryResp, error)
	WithdrawalCancel(ctx context.Context, in *WithdrawalCancelReq, opts ...grpc.CallOption) (*WithdrawalCancelResp, error)
	WithdrawalConfirm(ctx context.Context, in *WithdrawalConfirmReq, opts ...grpc.CallOption) (*WithdrawalConfirmResp, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) SettleHandle(ctx context.Context, in *SettleReq, opts ...grpc.CallOption) (*SettleResp, error) {
	out := new(SettleResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleHandle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SettleCancel(ctx context.Context, in *SettleCancelReq, opts ...grpc.CallOption) (*SettleCancelResp, error) {
	out := new(SettleCancelResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SettleConfirm(ctx context.Context, in *SettleConfirmReq, opts ...grpc.CallOption) (*SettleConfirmResp, error) {
	out := new(SettleConfirmResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) Balance(ctx context.Context, in *BalanceReq, opts ...grpc.CallOption) (*BalanceResp, error) {
	out := new(BalanceResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/Balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) DepositTry(ctx context.Context, in *DepositTryReq, opts ...grpc.CallOption) (*DepositTryResp, error) {
	out := new(DepositTryResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/DepositTry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) DepositCancel(ctx context.Context, in *DepositCancelReq, opts ...grpc.CallOption) (*DepositCancelResp, error) {
	out := new(DepositCancelResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/DepositCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) DepositConfirm(ctx context.Context, in *DepositConfirmReq, opts ...grpc.CallOption) (*DepositConfirmResp, error) {
	out := new(DepositConfirmResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/DepositConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WithdrawalTry(ctx context.Context, in *WithdrawalTryReq, opts ...grpc.CallOption) (*WithdrawalTryResp, error) {
	out := new(WithdrawalTryResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/WithdrawalTry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WithdrawalCancel(ctx context.Context, in *WithdrawalCancelReq, opts ...grpc.CallOption) (*WithdrawalCancelResp, error) {
	out := new(WithdrawalCancelResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/WithdrawalCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) WithdrawalConfirm(ctx context.Context, in *WithdrawalConfirmReq, opts ...grpc.CallOption) (*WithdrawalConfirmResp, error) {
	out := new(WithdrawalConfirmResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/WithdrawalConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility
type WalletServer interface {
	SettleHandle(context.Context, *SettleReq) (*SettleResp, error)
	SettleCancel(context.Context, *SettleCancelReq) (*SettleCancelResp, error)
	SettleConfirm(context.Context, *SettleConfirmReq) (*SettleConfirmResp, error)
	Balance(context.Context, *BalanceReq) (*BalanceResp, error)
	DepositTry(context.Context, *DepositTryReq) (*DepositTryResp, error)
	DepositCancel(context.Context, *DepositCancelReq) (*DepositCancelResp, error)
	DepositConfirm(context.Context, *DepositConfirmReq) (*DepositConfirmResp, error)
	WithdrawalTry(context.Context, *WithdrawalTryReq) (*WithdrawalTryResp, error)
	WithdrawalCancel(context.Context, *WithdrawalCancelReq) (*WithdrawalCancelResp, error)
	WithdrawalConfirm(context.Context, *WithdrawalConfirmReq) (*WithdrawalConfirmResp, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (UnimplementedWalletServer) SettleHandle(context.Context, *SettleReq) (*SettleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleHandle not implemented")
}
func (UnimplementedWalletServer) SettleCancel(context.Context, *SettleCancelReq) (*SettleCancelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleCancel not implemented")
}
func (UnimplementedWalletServer) SettleConfirm(context.Context, *SettleConfirmReq) (*SettleConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleConfirm not implemented")
}
func (UnimplementedWalletServer) Balance(context.Context, *BalanceReq) (*BalanceResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (UnimplementedWalletServer) DepositTry(context.Context, *DepositTryReq) (*DepositTryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositTry not implemented")
}
func (UnimplementedWalletServer) DepositCancel(context.Context, *DepositCancelReq) (*DepositCancelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositCancel not implemented")
}
func (UnimplementedWalletServer) DepositConfirm(context.Context, *DepositConfirmReq) (*DepositConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositConfirm not implemented")
}
func (UnimplementedWalletServer) WithdrawalTry(context.Context, *WithdrawalTryReq) (*WithdrawalTryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawalTry not implemented")
}
func (UnimplementedWalletServer) WithdrawalCancel(context.Context, *WithdrawalCancelReq) (*WithdrawalCancelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawalCancel not implemented")
}
func (UnimplementedWalletServer) WithdrawalConfirm(context.Context, *WithdrawalConfirmReq) (*WithdrawalConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawalConfirm not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_SettleHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleHandle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleHandle(ctx, req.(*SettleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SettleCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleCancel(ctx, req.(*SettleCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SettleConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleConfirm(ctx, req.(*SettleConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).Balance(ctx, req.(*BalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_DepositTry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositTryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).DepositTry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/DepositTry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).DepositTry(ctx, req.(*DepositTryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_DepositCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).DepositCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/DepositCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).DepositCancel(ctx, req.(*DepositCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_DepositConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).DepositConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/DepositConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).DepositConfirm(ctx, req.(*DepositConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WithdrawalTry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalTryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WithdrawalTry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/WithdrawalTry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WithdrawalTry(ctx, req.(*WithdrawalTryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WithdrawalCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WithdrawalCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/WithdrawalCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WithdrawalCancel(ctx, req.(*WithdrawalCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_WithdrawalConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawalConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).WithdrawalConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/WithdrawalConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).WithdrawalConfirm(ctx, req.(*WithdrawalConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SettleHandle",
			Handler:    _Wallet_SettleHandle_Handler,
		},
		{
			MethodName: "SettleCancel",
			Handler:    _Wallet_SettleCancel_Handler,
		},
		{
			MethodName: "SettleConfirm",
			Handler:    _Wallet_SettleConfirm_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _Wallet_Balance_Handler,
		},
		{
			MethodName: "DepositTry",
			Handler:    _Wallet_DepositTry_Handler,
		},
		{
			MethodName: "DepositCancel",
			Handler:    _Wallet_DepositCancel_Handler,
		},
		{
			MethodName: "DepositConfirm",
			Handler:    _Wallet_DepositConfirm_Handler,
		},
		{
			MethodName: "WithdrawalTry",
			Handler:    _Wallet_WithdrawalTry_Handler,
		},
		{
			MethodName: "WithdrawalCancel",
			Handler:    _Wallet_WithdrawalCancel_Handler,
		},
		{
			MethodName: "WithdrawalConfirm",
			Handler:    _Wallet_WithdrawalConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
