// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: wallet.proto

package wallet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalletClient is the client API for Wallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletClient interface {
	SettleHandle(ctx context.Context, in *SettleReq, opts ...grpc.CallOption) (*SettleResp, error)
	SettleCancel(ctx context.Context, in *SettleCancelReq, opts ...grpc.CallOption) (*SettleCancelResp, error)
	SettleConfirm(ctx context.Context, in *SettleConfirmReq, opts ...grpc.CallOption) (*SettleConfirmResp, error)
}

type walletClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletClient(cc grpc.ClientConnInterface) WalletClient {
	return &walletClient{cc}
}

func (c *walletClient) SettleHandle(ctx context.Context, in *SettleReq, opts ...grpc.CallOption) (*SettleResp, error) {
	out := new(SettleResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleHandle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SettleCancel(ctx context.Context, in *SettleCancelReq, opts ...grpc.CallOption) (*SettleCancelResp, error) {
	out := new(SettleCancelResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleCancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletClient) SettleConfirm(ctx context.Context, in *SettleConfirmReq, opts ...grpc.CallOption) (*SettleConfirmResp, error) {
	out := new(SettleConfirmResp)
	err := c.cc.Invoke(ctx, "/wallet.Wallet/SettleConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServer is the server API for Wallet service.
// All implementations must embed UnimplementedWalletServer
// for forward compatibility
type WalletServer interface {
	SettleHandle(context.Context, *SettleReq) (*SettleResp, error)
	SettleCancel(context.Context, *SettleCancelReq) (*SettleCancelResp, error)
	SettleConfirm(context.Context, *SettleConfirmReq) (*SettleConfirmResp, error)
	mustEmbedUnimplementedWalletServer()
}

// UnimplementedWalletServer must be embedded to have forward compatible implementations.
type UnimplementedWalletServer struct {
}

func (UnimplementedWalletServer) SettleHandle(context.Context, *SettleReq) (*SettleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleHandle not implemented")
}
func (UnimplementedWalletServer) SettleCancel(context.Context, *SettleCancelReq) (*SettleCancelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleCancel not implemented")
}
func (UnimplementedWalletServer) SettleConfirm(context.Context, *SettleConfirmReq) (*SettleConfirmResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SettleConfirm not implemented")
}
func (UnimplementedWalletServer) mustEmbedUnimplementedWalletServer() {}

// UnsafeWalletServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServer will
// result in compilation errors.
type UnsafeWalletServer interface {
	mustEmbedUnimplementedWalletServer()
}

func RegisterWalletServer(s grpc.ServiceRegistrar, srv WalletServer) {
	s.RegisterService(&Wallet_ServiceDesc, srv)
}

func _Wallet_SettleHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleHandle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleHandle(ctx, req.(*SettleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SettleCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleCancelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleCancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleCancel(ctx, req.(*SettleCancelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wallet_SettleConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleConfirmReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServer).SettleConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wallet.Wallet/SettleConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServer).SettleConfirm(ctx, req.(*SettleConfirmReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Wallet_ServiceDesc is the grpc.ServiceDesc for Wallet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wallet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.Wallet",
	HandlerType: (*WalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SettleHandle",
			Handler:    _Wallet_SettleHandle_Handler,
		},
		{
			MethodName: "SettleCancel",
			Handler:    _Wallet_SettleCancel_Handler,
		},
		{
			MethodName: "SettleConfirm",
			Handler:    _Wallet_SettleConfirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
